version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    container_name: k6-load-test
    volumes:
      - ./load-test.js:/scripts/load-test.js:ro
    command: run /scripts/load-test.js
    depends_on:
      - todoapi
    networks:
      - todo-network
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

  influxdb:
    image: influxdb:2.7-alpine
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - todo-network

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - todo-network

volumes:
  influxdb_data:
  grafana_data:

networks:
  todo-network:
    driver: bridge

